#!/usr/bin/env bash
source ${MINECRAFT_SCRIPT_DIR}/vars # import relevant environment variables from file

if [ "$1" == "start" ]; then # Start BDS server
  if ! screen -list | grep -q ${SCREEN_NAME}; then
    echo "Starting Minecraft Bedrock Dedicated Server..."
    screen -L -Logfile ${SERVER_ROOT}/${LOG_DIR}/latest.log -dmS ${SCREEN_NAME} bash ${SERVER_ROOT}/${SCRIPT_DIR}/start.sh
  else
    echo "There is an instance of Minecraft Bedrock Dedicated Server already running."
  fi
  echo "Open console by using 'minecraft login'"
elif [ "$1" == "update" ]; then # update server software
  bash ${SERVER_ROOT}/${SCRIPT_DIR}/update.sh
elif [ "$1" == "backup" ]; then # backup world files
  bash ${SERVER_ROOT}/${SCRIPT_DIR}/backup.sh
elif [ "$1" == "login" ]; then # login to console
  screen -Dr ${SCREEN_NAME}
else
  echo "Usage: minecraft <start|update|backup|login>"
fi
